server:
  port: 8500


spring:
  datasource:
    url: jdbc:h2:mem:ecommerce_dev_db_product;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  #flyway:
  #  baseline-on-migrate: true
  #  enabled: true



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG