
server:
  servlet:
    context-path: /user-service


spring:
   zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
   application:
    name: USER-SERVICE
   profiles:
    active:
    - dev
    
    
    
    